### ISSUE TITLE
ssh.service.d -> sshd.service.d in Ubuntu-24.04-Server

### ISSUE THREAD

**Issue by funk-on-code** [TommyTran732/Linux-Setup-Scripts#16]
So, if line 58 says:

`sudo chmod 755 /etc/systemd/system/sshd.service.d/`

Shouldn't 60 and 61, be directed to **sshd** too, rather than:

```
unpriv curl -s https://raw.githubusercontent.com/GrapheneOS/infrastructure/main/systemd/system/sshd.service.d/local.conf | sudo tee /etc/systemd/system/ssh.service.d/override.conf > /dev/null
sudo chmod 644 /etc/systemd/system/ssh.service.d/override.conf
```

Especially given the curl pull is from **sshd.service.d** ?

Caught while seeing the things the arch installer grabs from here.

**Comment by TommyTran732** [comment]
No because Ubuntu names it ssh.service /shrug

<img width="443" alt="Screenshot 2024-08-10 at 13 22 48" src="https://github.com/user-attachments/assets/c4419fe5-0835-4a37-9292-13f11e1fd7b9">
