### ISSUE TITLE
Proxmox ceph repository needs to be changed

### ISSUE THREAD

**Issue by mce0** [TommyTran732/Linux-Setup-Scripts#8]
After installing and updating proxmox with your script I get the following error:
`E: Failed to fetch https://enterprise.proxmox.com/debian/ceph-quincy/dists/bookworm/InRelease  401  Unauthorized`

To fix this the repository for ceph needs to be changed from enterprise to no-subscription. This can be changed in /etc/apt/sources.list.d/ceph.list
`deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription`

Alternatively you can run the following command:
`pveceph install --repository no-subscription`

**Comment by TommyTran732** [comment]
Fixed in https://github.com/TommyTran732/Linux-Setup-Scripts/commit/f6a88e32e84a34513046b31e098a7387a07ccd63, thanks for reporting
